### ISSUE TITLE
Problem calling right menu from another storyboard

### ISSUE THREAD

**Issue by FedericoSub** [iDevelopper/PBRevealViewController#64]
Hello,
I’m trying to call a TableviewController with right menu from another storyboard but doesn’t work ….
I call the button “vaiBtn” but nothing happens.
I think it's my mistake but I can't solve.

This is the ViewController in storyboard named “Immersioni” where I call the TableView in storyboard “Main”:

//
//  PostViewController.swift
//  CSMApp
//
//  Created by Federico Vivian on 10/02/2019.
//  Copyright © 2019 Club Sommozzatori Mestre. All rights reserved.
//

import UIKit

class PostViewController: UIViewController {

    override func viewDidLoad() {
        super.viewDidLoad()

        // Do any additional setup after loading the view.
    }
    
    @IBAction func vaiBtn(_ sender: Any) {
      
let mainStoryboard:UIStoryboard = UIStoryboard(name: "Main", bundle: nil)
            let desController = mainStoryboard.instantiateViewController(withIdentifier: "VetrinaTableViewController") as! VetrinaTableViewController
            let newFrontViewController = UINavigationController.init(rootViewController:desController)
            revealViewController()?.pushMainViewController(newFrontViewController, animated: true)

    
    }
    
  
}

-----------------------------------------------------------------

This is  the viewDidLoad() of VetrinaTableViewController in the other Storyboard

override func viewDidLoad() {
              
        super.viewDidLoad()
        indiceRiga = 0
       
        rightButton.target = self.revealViewController()
        self.revealViewController()?.isRightPresentViewOnTop = false
        rightButton.action = #selector(PBRevealViewController.revealRightView)
        
        updateView()
     
        //MARK make navbar trasparent
        let bar:UINavigationBar! =  self.navigationController?.navigationBar
        bar.setBackgroundImage(UIImage(), for: UIBarMetrics.default)
        bar.shadowImage = UIImage()
         self.tableView.addSubview(RefreshControl)
    }

--------------------

Thanks in advance.
Federico

**Comment by iDevelopper** [comment]
No sure to understand.

1) How do you instantiate PBRevealViewController? Programmatically?
2) Which controller is in the main storyboard? (main, right ?)
3) Which controller is in the Immersioni storyboard? (main, right)

**Comment by FedericoSub** [comment]
1) yes 1. Programmatically
2) yes main and right
3) in Immersioni storyboard i have a ViewController with only a button "Pubblica in Vetrina" where i'd like put the return to VetrinaTableViewController .

This i VetrinaTableViewController  in main storyboard where I'd like to return
![img_0483](https://user-images.githubusercontent.com/35109594/52583276-8028aa00-2e2f-11e9-9324-7c5237e08424.jpg)

This is in Immersioni storyboard where I select my dive number for display the detail
![img_0485](https://user-images.githubusercontent.com/35109594/52583385-bebe6480-2e2f-11e9-80d8-907488a53e56.jpg)

this is dive detail  DiveTableViewController
![img_0486](https://user-images.githubusercontent.com/35109594/52583456-f4634d80-2e2f-11e9-8851-801a59827a6c.jpg)

from DiveTableViewController I go to PostViewController, this is PostViewController where if I push button "Pubblica in Vetrina" I should return to VetrinaTableViewController

![img_0487](https://user-images.githubusercontent.com/35109594/52583521-16f56680-2e30-11e9-9481-b373c9c929bc.jpg)
[Archivio.zip](https://github.com/iDevelopper/PBRevealViewController/files/2852403/Archivio.zip)

**Comment by iDevelopper** [comment]
Hum... Can you upload the whole project please?

**Comment by FedericoSub** [comment]
It's 140MB so this is a link in Dropbox


https://www.dropbox.com/s/6kpeh2i6eu2x1tr/CSMApp.zip?dl=0


Thanks

**Comment by iDevelopper** [comment]
Got it. I have a look.

**Comment by iDevelopper** [comment]
Sorry I do not find how to go to this view!

**Comment by FedericoSub** [comment]
logbook > Immersioni > #3 > Pubblica (button at the end) > Pubblica in Vetrina

**Comment by FedericoSub** [comment]
this is a Sreenrecording how you can finf the final view....
https://www.dropbox.com/s/4n3u0p9615oz8s6/ScreenRecording_02-12-2019%2013-37-12.MP4?dl=0

thanks

**Comment by iDevelopper** [comment]
Well, RevealViewController is nil in PostViewController, but that, I suspected it from the beginning.

You have no more reveal view controller as soon as you present a modal controller. Because the new presented controller is no more in the same stack. 

This is the case when you present another navigation view controller with a show segue type in a storyboard. For example, to present ListaDiveTableViewController, you use a show segue to the entry point of immersioni storyboard which is a navigation controller. So ListaDiveTableViewController is presented modally and you lost the reveal view controller.

Now there are two solutions for you:

Either you continue like this, modally presenting the controllers and you have to pass the reference of the reveal view controller in the prepareforsegue method to the destination controller, or you remove too many navigation controllers so that the presented controllers remain in the stack. I suggest the second solution as it corresponds better to the logic of presentation of the views (table view with the arrow accessory etc ...).

So first the entry point of the immersioni storyboard should be the ListaDiveTableViewController and not a navigation controller. It will be presented in the stack and it will have access to the reveal view controller instance. Just set a background color to the navigation bar to see the back button and the right bar item too.

After, in immersioni storyboard too, the segueDiveDettaglio segue should point to the DiveTableViewController and not to a navigation controller. So you have also to change your code in ListaDiveTableViewController.swift:

```
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        
        if  segue.identifier == "segueDiveDettaglio"
        {
            /*
            let destination = segue.destination as! UINavigationController
            let guest = destination.topViewController as! DiveTableViewController
            */
            let guest = segue.destination as! DiveTableViewController
            let indexPath = self.tableView.indexPath(for: sender as! UITableViewCell)!
            guest.idDivePass = self.dive[indexPath.row].idDive
        }
    }
```

Finally, in PostViewController, replace push with set (because push present a new child view controller only if the right menu is open, you should use also a popToRootViewController to go back to the first controller of the navigation stack).

```
    @IBAction func vaiBtn(_ sender: Any) {
        let mainStoryboard:UIStoryboard = UIStoryboard(name: "Main", bundle: nil)
        let desController = mainStoryboard.instantiateViewController(withIdentifier: "VetrinaTableViewController") as! VetrinaTableViewController
        let newFrontViewController = UINavigationController.init(rootViewController:desController)
        print("reveal: \(String(describing: revealViewController()))")
        //revealViewController()?.pushMainViewController(newFrontViewController, animated: true)
        revealViewController()?.setMainViewController(newFrontViewController, animated: true)
    }
```
There is a lot of views in your application and I was also busy by the way, so the answer is a bit late. But your application will be great.

I hope this answer will help you.

**Comment by FedericoSub** [comment]
Ok thanks a lot I'll try with your suggestion...

**Comment by iDevelopper** [comment]
Welcome, let me know if you need, keep me informed.
