### ISSUE TITLE
PBRevealViewController and using IB Traits Variations

### ISSUE THREAD

**Issue by ghost** [iDevelopper/PBRevealViewController#71]

**Comment by DonaldLaborde** [comment]
Hi all, I know that PBRevealViewcontroller has nothing to do with IB Traits Variations directly, but since I've implemented PBRevealViewController and Traits Variations, I've noticed something strange.
I have two targets for the same application, target members are checked in IB, Main_iPhone.storyboard is the same for both targets.
However I notice a difference on simulator and physics for iPhones X..., I do not find why?
If anyone could give me an idea I would appreciate
Thanks in advance.
![2019-05-12_10-33-05](https://user-images.githubusercontent.com/3705917/57580255-93d3c300-74a7-11e9-816f-f5da2b88d1ae.png)

**Comment by iDevelopper** [comment]
Hey there, this looks like a great example of a question that you should ask on StackOverflow where people can help out with questions like this. I try to keep the PBRevealViewController issues focused only on bug or help reports for the framework, and for upcoming feature requests. Which this doesn't look like. However you will have to elaborate a bit more because I do not see the relation between having two targets and the differences of layout between the simulator and a real device. In fact I do not understand the question! Closing this issue.

**Comment by ghost** [comment]
Oh yes ok, you're right, sorry for the noise.
